version: 2

sources:
  - name: raw
    catalog: olist
    schema: olist_daily
    

    tables:
      - name: customers
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: record_updated_at

      - name: order_items
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: record_updated_at
      - name: payments
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: record_updated_at
      - name: orders
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: record_updated_at
      - name: reviews
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: record_updated_at
      - name: products
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: record_updated_at

      - name: sellers
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 2, period: day}
          loaded_at_field: record_updated_at

  

  - name: raw_static
    catalog: olist
    schema: simulated

    tables:
      - name: geolocation